version: 2.1

#-----------------------------------------------------------------------------
# packcheck-0.4.2
# Packcheck global environment variables
#-----------------------------------------------------------------------------

env: &env
    environment:
      # ------------------------------------------------------------------------
      # Common options
      # ------------------------------------------------------------------------
      # GHC_OPTIONS: "-Werror"
      CABAL_REINIT_CONFIG: "y"

#-----------------------------------------------------------------------------
# Common utility stuff, not to be modified usually
#-----------------------------------------------------------------------------

preinstall: &preinstall
  run: |
        echo "****CABAL_REINIT_CONFIG-preinstall-begin=$CABAL_REINIT_CONFIG"

#-----------------------------------------------------------------------------
# Build matrix
#-----------------------------------------------------------------------------

jobs:
  cabal-ghc-8-6-5:
      <<: *env
      steps:
        - checkout
        - *preinstall
        - run: |
              echo "****CABAL_REINIT_CONFIG=$CABAL_REINIT_CONFIG"

workflows:
  version: 2.1
  build:
    jobs:
      - cabal-ghc-8-6-5
